# Generated by Django 5.0.6 on 2024-08-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_generalitem_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalitem",
            name="name",
            field=models.CharField(default=str, max_length=356),
            preserve_default=False,
        ),
    ]
